
# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "reports/workflow.rst"

import {{ cookiecutter.repo_name }} as project

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

rule make_dataset:
    conda: "environment.yml"
    input: 
    script: "{{ cookiecutter.repo_name }}/data/make_dataset.py"